name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'kubernetes/deployment.yaml'
      - '**/*.md'
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm test || echo "No tests found"

  lint:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test, lint]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/

  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: [build]
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    outputs:
      image_tag: ${{ steps.set_output.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist/
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long,prefix=sha-
      - name: Set image tag output
        id: set_output
        run: echo "image_tag=${{ steps.meta.outputs.version }}" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          load: true
      - uses: aquasecurity/trivy-action@master
        with:
          image-ref: "${{ steps.meta.outputs.tags }}"
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # OPTIONAL: Safer image cleanup (disabled by default)
      - name: Smart Image Cleanup
        if: always()
        run: |
          echo "🔍 Starting intelligent image cleanup..."
          
          # Configuration
          OWNER="khannashiv"
          PACKAGE_NAME="project-cicd-github-actions"
          API_URL="https://api.github.com/users/$OWNER/packages/container/$PACKAGE_NAME/versions"
          
          # Get all versions with full metadata
          echo "📦 Fetching package versions..."
          RESPONSE=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "$API_URL?per_page=100")
          
          # Process versions - prioritize tagged, but keep untagged manifest
          echo "🧠 Analyzing versions..."
          KEEPER_DATA=$(echo "$RESPONSE" | jq -r '
            [.[] | select(.metadata.container.tags != [])] 
            | sort_by(.created_at) 
            | reverse 
            | .[0] | {id: .id, tags: .metadata.container.tags[0]}')
          
          KEEPER_ID=$(echo "$KEEPER_DATA" | jq -r '.id')
          KEEPER_TAG=$(echo "$KEEPER_DATA" | jq -r '.tags')
          
          # Find the untagged manifest for this commit
          UNTAGGED_ID=$(echo "$RESPONSE" | jq -r --arg tag "$KEEPER_TAG" '
            .[] | select(.metadata.container.tags == [] and .name == $tag) | .id')
          
          echo "💎 Keeping tagged: $KEEPER_TAG ($KEEPER_ID)"
          echo "📌 Keeping untagged: $UNTAGGED_ID"
          
          # Delete all other versions
          echo "$RESPONSE" | jq -r '.[].id' | while read VERSION_ID; do
            if [[ "$VERSION_ID" != "$KEEPER_ID" && "$VERSION_ID" != "$UNTAGGED_ID" ]]; then
              echo "🗑️ Deleting $VERSION_ID"
              curl -X DELETE \
                -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
                "$API_URL/$VERSION_ID"
              sleep 1.5
            fi
          done
          
          # Final verification
          echo "✅ Cleanup complete. Final state:"
          curl -s \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "$API_URL" | jq '.[] | {id: .id, tags: .metadata.container.tags}'
        
  update-k8s:
    name: Update Kubernetes Deployment
    runs-on: ubuntu-latest
    needs: [docker]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - run: |
          NEW_IMAGE="ghcr.io/${{ github.repository }}:${{ needs.docker.outputs.image_tag }}"
          sed -i "s|image: ghcr.io/.*|image: ${NEW_IMAGE}|g" kubernetes/deployment.yaml
          echo "Updated deployment to use image: ${NEW_IMAGE}"
      - run: |
          git add kubernetes/deployment.yaml
          git commit -m "Update K8s deployment with image: ${{ needs.docker.outputs.image_tag }} [skip ci]" || echo "No changes to commit"
          git push

  cleanup:
    name: Cleanup Old Workflow Runs
    runs-on: ubuntu-latest
    needs: [update-k8s]
    steps:
      - run: |
          RUNS=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100" \
            | jq -r '.workflow_runs | sort_by(.created_at) | .[] | select(.status == "completed") | .id')
          
          TO_DELETE=$(echo "$RUNS" | tail -n +2)
          echo "Runs to delete: $TO_DELETE"
          
          for RUN_ID in $TO_DELETE; do
            echo "Deleting run $RUN_ID"
            curl -X DELETE \
              -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID"
          done