name: CI/CD Pipeline

on:
  push:
    branches: [ main ] # Trigger on push to main branch
    paths-ignore:
      - 'kubernetes/deployment.yaml' # Ignore changes to deployment.yaml
      - '**/*.md'                    # Ignore markdown files
  pull_request:
    branches: [ main ] # Trigger on PRs to main branch

jobs:
  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Checkout code
      - uses: actions/setup-node@v4 # Setup Node.js
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci # Install dependencies
      - run: npm test || echo "No tests found" # Run tests, don't fail if none

  lint:
    name: Static Code Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Checkout code
      - uses: actions/setup-node@v4 # Setup Node.js
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci # Install dependencies
      - run: npm run lint # Run linter

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test, lint] # Wait for test and lint jobs
    steps:
      - uses: actions/checkout@v4 # Checkout code
      - uses: actions/setup-node@v4 # Setup Node.js
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci # Install dependencies
      - run: npm run build # Build project
      - uses: actions/upload-artifact@v4 # Upload build output
        with:
          name: build-artifacts
          path: dist/

  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    needs: [build] # Wait for build job
    env:
      REGISTRY: ghcr.io # GitHub Container Registry
      IMAGE_NAME: ${{ github.repository }} # Image name
    outputs:
      image_tag: ${{ steps.set_output.outputs.image_tag }} # Output image tag for later jobs
    steps:
      - uses: actions/checkout@v4 # Checkout code
      - uses: actions/download-artifact@v4 # Download build artifacts
        with:
          name: build-artifacts
          path: dist/
      - uses: docker/setup-buildx-action@v3 # Setup Docker Buildx
      - uses: docker/login-action@v3 # Login to registry
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - uses: docker/metadata-action@v5 # Generate Docker image metadata/tags
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long,prefix=sha-
      - name: Set image tag output # Set image tag for use in later jobs
        id: set_output
        run: echo "image_tag=${{ steps.meta.outputs.version }}" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v5 # Build Docker image (local load, not pushed yet)
        with:
          context: .
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          load: true
      - uses: aquasecurity/trivy-action@master # Scan image for vulnerabilities
        with:
          image-ref: "${{ steps.meta.outputs.tags }}"
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
      - uses: docker/build-push-action@v5 # Push Docker image to registry
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

        # OPTIONAL: Safer image cleanup (disabled by default)
        # Placeholder for future registry cleanup steps

  update-k8s:
    name: Update Kubernetes Deployment
    runs-on: ubuntu-latest
    needs: [docker] # Wait for docker job
    if: github.ref == 'refs/heads/main' && github.event_name == 'push' # Only on main branch push
    steps:
      - uses: actions/checkout@v4 # Checkout code (with push token)
        with:
          token: ${{ secrets.TOKEN }}
      - run: |
          git config user.name "GitHub Actions" # Set git user
          git config user.email "actions@github.com"
      - run: |
          NEW_IMAGE="ghcr.io/${{ github.repository }}:${{ needs.docker.outputs.image_tag }}"
          sed -i "s|image: ghcr.io/.*|image: ${NEW_IMAGE}|g" kubernetes/deployment.yaml # Update image in deployment.yaml
          echo "Updated deployment to use image: ${NEW_IMAGE}"
      - run: |
          git add kubernetes/deployment.yaml
          git commit -m "Update K8s deployment with image: ${{ needs.docker.outputs.image_tag }} [skip ci]" || echo "No changes to commit"
          git push # Commit and push changes

  cleanup:
    name: Cleanup Old Workflow Runs
    runs-on: ubuntu-latest
    needs: [update-k8s] # Wait for update-k8s job
    steps:
      - run: |
          # Get list of completed workflow runs, except the latest
          RUNS=$(curl -s \
            -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?per_page=100" \
            | jq -r '.workflow_runs | sort_by(.created_at) | .[] | select(.status == "completed") | .id')
          
          TO_DELETE=$(echo "$RUNS" | tail -n +2)
          echo "Runs to delete: $TO_DELETE"
          
          # Delete old workflow runs
          for RUN_ID in $TO_DELETE; do
            echo "Deleting run $RUN_ID"
            curl -X DELETE \
              -H "Authorization: Bearer ${{ secrets.TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/runs/$RUN_ID"
          done